/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.example.command.AddRestaurantCommand;
import org.example.command.AddPlateCommand;
import org.example.command.DeleteRestaurantCommand;
import org.example.command.UserMenu;
import org.example.controllers.MenuController;
import org.example.controllers.RestaurantController;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {

        RestaurantController restaurantController = new RestaurantController();
         MenuController menuController = new MenuController();

        UserMenu menu = new UserMenu();
        menu.addCommand(1, new AddRestaurantCommand(restaurantController));
        menu.addCommand(3, new DeleteRestaurantCommand(restaurantController));
        menu.addCommand(4, new AddPlateCommand(menuController));

        menu.showMenu();
    }
}
