/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.example.command.*;
import org.example.controllers.MenuController;
import org.example.controllers.RestaurantController;
import org.example.controllers.ReviewController;

public class App {

    public static void main(String[] args) {

        RestaurantController restaurantController = new RestaurantController();
        MenuController menuController = new MenuController();
        ReviewController reviewController = new ReviewController();

        UserMenu menu = new UserMenu();
        menu.addCommand(1, new AddRestaurantCommand(restaurantController));
        menu.addCommand(2, new EditRestaurantCommand(restaurantController));
        menu.addCommand(3, new DeleteRestaurantCommand(restaurantController));
        menu.addCommand(4, new GetRestaurantsCommand(restaurantController));
        menu.addCommand(5, new AddPlateCommand(menuController));
        menu.addCommand(6, new EditMenuCommand(menuController));
        menu.addCommand(7, new DeletePlateCommand(menuController));
        menu.addCommand(8, new GetMenuCommand(menuController));
        menu.addCommand(9, new AddRestaurantReviewCommand(reviewController));
        menu.addCommand(10, new AddPlateReviewCommand(reviewController));
        menu.addCommand(11, new GetReviewsRestaurant(reviewController));
        menu.addCommand(12, new GetReviewsPlate(reviewController));

        menu.showMenu();
    }
}
